[package]
name = "portone-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "PortOne CLI"
publish = false

[[bin]]
name = "portone"
path = "src/main.rs"

[dependencies]
anstream = "1.0.0"
anstyle = "1.0.14"
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive", "env", "wrap_help"] }
include_dir = "0.7.4"
indicatif = "0.18.6"
inquire = "0.9.4"
serde_json = { version = "1.0.151", features = ["arbitrary_precision", "preserve_order"] }

[dev-dependencies]
tempfile = "3.27.0"
