[package]
name = "portone-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "PortOne CLI"
publish = false

[[bin]]
name = "portone"
path = "src/main.rs"

[dependencies]
anstream = "1.0.0"
anstyle = "1.0.14"
anyhow = "1.0.104"
base64 = "0.23.1"
clap = { version = "4.6.6", features = ["derive", "env", "wrap_help"] }
etcetera = "0.11.0"
getrandom = "0.2.17"
humantime = "2.4.0"
include_dir = "0.7.4"
indicatif = "0.18.6"
inquire = "0.9.4"
keyring = { version = "4.2.0", default-features = false, features = ["v1"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["arbitrary_precision", "preserve_order"] }
sha2 = "0.11.0"
toml = "1.1.4"
ureq = { version = "3.4.0", features = ["json", "platform-verifier"] }
url = "2.5.8"

[dev-dependencies]
assert_cmd = "2.2.2"
httpmock = "0.8.3"
predicates = "3.1.4"
tempfile = "3.27.0"
